import Image from 'next/image'
import Link from 'next/link'
import type { LandingPage, LandingSection } from '@/lib/landing-pages/types'
import type { StorefrontProduct } from '@/lib/services/storefront-utils'
import { getStartingPrice } from '@/lib/services/storefront-utils'

function ProductPanel({ product, title, body, ctaLabel }: { product: StorefrontProduct; title?: string; body?: string; ctaLabel?: string }) {
  const image = product.images.find((item) => item.is_primary) ?? product.images[0]
  return <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="grid gap-6 p-5 sm:grid-cols-[160px_1fr] sm:p-7">{image ? <Image src={image.image_url} alt={image.alt_text || product.name} width={320} height={320} className="aspect-square w-full rounded-2xl bg-slate-100 object-contain" /> : <div className="aspect-square rounded-2xl bg-slate-100" />}<div className="flex flex-col justify-center"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-700">{product.brand?.name || 'SahiGadget catalogue'}</p><h3 className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{title || product.name}</h3>{body ? <p className="mt-3 text-sm leading-6 text-slate-600">{body}</p> : product.short_description ? <p className="mt-3 text-sm leading-6 text-slate-600">{product.short_description}</p> : null}<div className="mt-5 flex flex-wrap items-center gap-4"><span className="text-xl font-black text-emerald-700">{getStartingPrice(product) !== null ? `৳${getStartingPrice(product)?.toLocaleString('en-BD')}` : 'View current price'}</span><Link href={`/products/${product.slug}`} data-analytics-event="landing_page_product_cta" data-landing-section={title || product.name} className="inline-flex h-11 items-center rounded-xl bg-slate-950 px-5 text-sm font-bold text-white transition hover:bg-emerald-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500 focus-visible:ring-offset-2">{ctaLabel || 'View product'}</Link></div></div></div></article>
}

function Section({ section, products }: { section: LandingSection; products: StorefrontProduct[] }) {
  if (section.type === 'announcement') return <section className={`rounded-2xl border p-4 text-center ${section.tone === 'amber' ? 'border-amber-200 bg-amber-50 text-amber-950' : section.tone === 'emerald' ? 'border-emerald-200 bg-emerald-50 text-emerald-950' : 'border-slate-200 bg-white text-slate-900'}`}><p className="text-xs font-bold uppercase tracking-[0.18em]">{section.eyebrow || 'SahiGadget update'}</p><h2 className="mt-1 text-lg font-bold">{section.title}</h2>{section.body ? <p className="mt-1 text-sm opacity-80">{section.body}</p> : null}</section>
  if (section.type === 'hero') return <section className="grid items-center gap-8 overflow-hidden rounded-[2rem] bg-slate-950 p-6 text-white sm:p-10 lg:grid-cols-[1fr_0.85fr]"><div><p className="text-xs font-bold uppercase tracking-[0.22em] text-emerald-300">{section.eyebrow || 'SahiGadget'}</p><h2 className="mt-3 max-w-2xl text-4xl font-semibold tracking-tight sm:text-5xl">{section.title}</h2>{section.body ? <p className="mt-5 max-w-xl text-base leading-7 text-slate-300">{section.body}</p> : null}{section.ctaLabel && section.ctaHref ? <Link href={section.ctaHref} data-analytics-event="landing_page_cta" data-landing-section={section.id} className="mt-7 inline-flex h-12 items-center rounded-xl bg-emerald-400 px-5 text-sm font-black text-slate-950 hover:bg-emerald-300 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-300 focus-visible:ring-offset-2 focus-visible:ring-offset-slate-950">{section.ctaLabel}</Link> : null}</div>{section.imageUrl ? <div className="relative min-h-[260px] overflow-hidden rounded-3xl bg-slate-900"><Image src={section.imageUrl} alt={section.imageAlt || section.title} fill className="object-cover" sizes="(max-width: 1024px) 100vw, 45vw" priority /></div> : <div className="hidden min-h-[260px] rounded-3xl bg-gradient-to-br from-emerald-400/30 to-cyan-400/10 lg:block" />}</section>
  if (section.type === 'features') return <section><h2 className="text-2xl font-semibold tracking-tight text-slate-950">{section.title}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{section.items.map((item) => <article key={`${section.id}-${item.title}`} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{item.title}</h3>{item.body ? <p className="mt-2 text-sm leading-6 text-slate-600">{item.body}</p> : null}</article>)}</div></section>
  if (section.type === 'product') { const product = products.find((item) => item.id === section.productId) || products[0]; return product ? <ProductPanel product={product} title={section.title} body={section.body} ctaLabel={section.ctaLabel} /> : null }
  if (section.type === 'trust') return <section className="rounded-3xl border border-emerald-100 bg-emerald-50/70 p-6"><h2 className="text-2xl font-semibold text-slate-950">{section.title}</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{section.items.map((item) => <li key={`${section.id}-${item}`} className="rounded-xl bg-white/80 p-4 text-sm font-semibold text-slate-800">{item}</li>)}</ul></section>
  if (section.type === 'faq') return <section><h2 className="text-2xl font-semibold tracking-tight text-slate-950">{section.title}</h2><div className="mt-5 divide-y divide-slate-200 rounded-2xl border border-slate-200 bg-white">{section.items.map((item) => <details key={`${section.id}-${item.question}`} className="group p-5"><summary className="cursor-pointer list-none pr-6 font-bold text-slate-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500">{item.question}</summary><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">{item.answer}</p></details>)}</div></section>
  if (section.type === 'rich_text') return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-2xl font-semibold text-slate-950">{section.title}</h2><p className="mt-3 whitespace-pre-line text-sm leading-7 text-slate-600">{section.body}</p></section>
  if (section.type === 'cta') return <section className="rounded-3xl bg-emerald-700 p-7 text-white sm:p-10"><h2 className="text-3xl font-semibold">{section.title}</h2>{section.body ? <p className="mt-3 max-w-2xl text-sm leading-6 text-emerald-50">{section.body}</p> : null}<Link href={section.href} data-analytics-event="landing_page_cta" data-landing-section={section.id} className="mt-6 inline-flex h-11 items-center rounded-xl bg-white px-5 text-sm font-black text-emerald-800 hover:bg-emerald-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-emerald-700">{section.label}</Link></section>
  return null
}

export function LandingPageRenderer({ page }: { page: LandingPage }) {
  const products = page.resolved_products ?? (page.linked_product ? [page.linked_product] : [])
  return <main data-analytics-event="landing_page_view" data-landing-page={page.slug} className="min-h-screen bg-slate-50 text-slate-950"><div className="mx-auto max-w-6xl px-4 py-5 sm:px-6 sm:py-8 lg:px-8"><header className="mb-8 flex items-center justify-between gap-4"><Link href="/" className="text-sm font-black tracking-tight text-slate-950">SahiGadget</Link><Link href="/products" className="text-sm font-bold text-emerald-700 hover:underline">Browse catalogue</Link></header>{page.hero_image_url ? <div className="relative mb-8 min-h-[220px] overflow-hidden rounded-[2rem] bg-slate-100 sm:min-h-[360px]"><Image src={page.mobile_hero_image_url || page.hero_image_url} alt={page.internal_name} fill className="object-cover sm:hidden" sizes="100vw" priority /><Image src={page.hero_image_url} alt={page.internal_name} fill className="hidden object-cover sm:block" sizes="(max-width: 1024px) 100vw, 1200px" priority /></div> : null}<div className="space-y-8">{page.sections.map((section) => <Section key={section.id} section={section} products={products} />)}</div></div></main>
}
