'use client'
/* eslint-disable @typescript-eslint/no-explicit-any -- server data is serialized from Supabase settings and relation responses; all mutations are server-validated. */

import { zodResolver } from '@hookform/resolvers/zod'
import { useState, useTransition } from 'react'
import { useForm } from 'react-hook-form'
import { FileText, Save, ShieldCheck, Store, Truck } from 'lucide-react'

import { saveAdminUser, saveOperationalSettings, saveOwnerSettings } from '@/lib/admin/actions'
import { adminUserSchema, settingsSchema } from '@/lib/admin/schema'

const inputClass = 'h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-900 outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100'
const labelClass = 'mb-1.5 block text-xs font-bold uppercase tracking-[0.12em] text-slate-600'

export function SettingsManager({ settings, auditLogs, admins, isOwner }: { settings: Record<string, any>; auditLogs: any[]; admins: any[]; isOwner: boolean }) {
  const [tab, setTab] = useState<'operational' | 'business' | 'audit' | 'access'>('operational')
  const tabs = [['operational', 'Delivery & warranty'], ...(isOwner ? [['business', 'Store & returns'], ['audit', 'Audit activity'], ['access', 'Access control']] as const : [])] as const
  return <div><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{tabs.map(([value, label]) => <button key={value} type="button" onClick={() => setTab(value)} className={`h-9 shrink-0 rounded-full px-4 text-sm font-semibold ${tab === value ? 'bg-slate-950 text-white' : 'bg-white text-slate-600 ring-1 ring-slate-200'}`}>{label}</button>)}</div>{tab === 'operational' ? <OperationalSettings initial={settings} /> : null}{tab === 'business' && isOwner ? <OwnerSettings initial={settings} /> : null}{tab === 'audit' && isOwner ? <AuditLog logs={auditLogs} /> : null}{tab === 'access' && isOwner ? <AdminAccess admins={admins} /> : null}</div>
}

function Notice({ message }: { message: string | null }) { return message ? <p role="status" className="mt-3 rounded-lg bg-slate-100 px-3 py-2 text-sm text-slate-700">{message}</p> : null }

function OperationalSettings({ initial }: { initial: Record<string, any> }) {
  const [message, setMessage] = useState<string | null>(null); const [isPending, startTransition] = useTransition()
  const form = useForm<any>({ resolver: zodResolver(settingsSchema.pick({ deliveryCharges: true, businessPolicy: true })), defaultValues: { deliveryCharges: initial.delivery_charges ?? { dhaka: 80, outside_dhaka: 130 }, businessPolicy: initial.business_policy ?? { guarantee_days: 7, service_warranty_years: 1, policy_text: '7 Days Guarantee & 1 Year Service Warranty. Manufacturer warranty terms apply where applicable.' } } })
  return <form className="grid gap-6 xl:grid-cols-2" onSubmit={form.handleSubmit((values) => startTransition(async () => { const result = await saveOperationalSettings(values); setMessage(result.message) }))}><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><Truck className="h-5 w-5" /></span><div><h2 className="font-semibold">Delivery charges</h2><p className="mt-1 text-sm text-slate-500">New orders snapshot the charge at checkout; existing orders are unchanged.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className={labelClass}>Dhaka (BDT)</label><input type="number" className={inputClass} {...form.register('deliveryCharges.dhaka')} /></div><div><label className={labelClass}>Outside Dhaka (BDT)</label><input type="number" className={inputClass} {...form.register('deliveryCharges.outside_dhaka')} /></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-700"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-semibold">Warranty & guarantee</h2><p className="mt-1 text-sm text-slate-500">Product-level policies may override this operational default.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className={labelClass}>Guarantee days</label><input type="number" className={inputClass} {...form.register('businessPolicy.guarantee_days')} /></div><div><label className={labelClass}>Service warranty years</label><input type="number" className={inputClass} {...form.register('businessPolicy.service_warranty_years')} /></div></div><div className="mt-4"><label className={labelClass}>Default policy text</label><textarea className="min-h-32 w-full rounded-lg border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" {...form.register('businessPolicy.policy_text')} /></div></section><div className="xl:col-span-2"><button disabled={isPending} className="inline-flex h-10 items-center gap-2 rounded-lg bg-emerald-600 px-4 text-sm font-semibold text-white"><Save className="h-4 w-4" />{isPending ? 'Saving…' : 'Save operational settings'}</button><Notice message={message} /></div></form>
}

function OwnerSettings({ initial }: { initial: Record<string, any> }) {
  const [message, setMessage] = useState<string | null>(null); const [isPending, startTransition] = useTransition()
  const form = useForm<any>({ resolver: zodResolver(settingsSchema.pick({ storeProfile: true, returnRefundPolicy: true })), defaultValues: { storeProfile: initial.store_profile ?? { business_name: 'SahiGadget Mobile Phone & Gadget Shop', established: 2019, tagline: 'সঠিক দাম, সঠিক গ্যাজেট', brand_promise: 'আসল পণ্য • দ্রুত ডেলিভারি • সারা দেশে সেবা', location: 'Araihazar, Narayanganj, Bangladesh – 1460', phone: '+880 1601-654316', public_email: 'www.sahigadget.com@gmail.com', admin_email: 'helpline.sahitech@gmail.com', currency: 'BDT', languages: ['Bangla', 'English'] }, returnRefundPolicy: initial.return_refund_policy ?? { policy_text: '' } } })
  return <form className="grid gap-6 xl:grid-cols-[1.1fr_.9fr]" onSubmit={form.handleSubmit((values) => startTransition(async () => { const result = await saveOwnerSettings(values); setMessage(result.message) }))}><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-950 text-white"><Store className="h-5 w-5" /></span><div><h2 className="font-semibold">Store profile</h2><p className="mt-1 text-sm text-slate-500">Owner-only source of truth for reusable business information.</p></div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div><label className={labelClass}>Business name</label><input className={inputClass} {...form.register('storeProfile.business_name')} /></div><div><label className={labelClass}>Established</label><input type="number" className={inputClass} {...form.register('storeProfile.established')} /></div><div><label className={labelClass}>Tagline</label><input className={inputClass} {...form.register('storeProfile.tagline')} /></div><div><label className={labelClass}>Brand promise</label><input className={inputClass} {...form.register('storeProfile.brand_promise')} /></div><div className="sm:col-span-2"><label className={labelClass}>Location</label><input className={inputClass} {...form.register('storeProfile.location')} /></div><div><label className={labelClass}>Phone</label><input className={inputClass} {...form.register('storeProfile.phone')} /></div><div><label className={labelClass}>Public email</label><input className={inputClass} {...form.register('storeProfile.public_email')} /></div><div className="sm:col-span-2"><label className={labelClass}>Admin email</label><input className={inputClass} {...form.register('storeProfile.admin_email')} /></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-700"><FileText className="h-5 w-5" /></span><div><h2 className="font-semibold">Return & refund policy</h2><p className="mt-1 text-sm text-slate-500">This is business configuration, not legal advice.</p></div></div><div className="mt-5"><label className={labelClass}>Policy text</label><textarea className="min-h-80 w-full rounded-lg border border-slate-200 p-3 text-sm leading-6 outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" {...form.register('returnRefundPolicy.policy_text')} /></div></section><div className="xl:col-span-2"><button disabled={isPending} className="inline-flex h-10 items-center gap-2 rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white"><Save className="h-4 w-4" />{isPending ? 'Saving…' : 'Save owner settings'}</button><Notice message={message} /></div></form>
}

function AuditLog({ logs }: { logs: any[] }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Administrative audit activity</h2><p className="mt-1 text-sm text-slate-500">Safe metadata only; credentials and sensitive identity data are excluded.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">When</th><th className="px-5 py-3">Action</th><th className="px-5 py-3">Entity</th><th className="px-5 py-3">Safe metadata</th></tr></thead><tbody>{logs.map((log) => <tr key={log.id} className="border-t border-slate-100"><td className="px-5 py-3 text-xs text-slate-500">{new Date(log.created_at).toLocaleString('en-BD')}</td><td className="px-5 py-3 font-semibold">{log.action}</td><td className="px-5 py-3 text-slate-600">{log.entity_type}</td><td className="max-w-96 truncate px-5 py-3 font-mono text-xs text-slate-500">{log.details ? JSON.stringify(log.details) : '—'}</td></tr>)}</tbody></table></div>{!logs.length ? <p className="p-6 text-sm text-slate-500">No administrative activity has been recorded yet.</p> : null}</section>
}

function AdminAccess({ admins }: { admins: any[] }) {
  const [message, setMessage] = useState<string | null>(null); const [isPending, startTransition] = useTransition()
  const form = useForm<any>({ resolver: zodResolver(adminUserSchema), defaultValues: { userId: '', fullName: '', email: '', role: 'STAFF', isActive: true } })
  return <div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">Grant or update access</h2><p className="mt-1 text-sm leading-6 text-slate-500">The user must first have an existing verified Supabase Auth identity. This form does not create passwords or transmit credentials.</p><form className="mt-5 space-y-4" onSubmit={form.handleSubmit((values: any) => startTransition(async () => { const result = await saveAdminUser(values); setMessage(result.message); if (result.ok) form.reset() }))}><div><label className={labelClass}>Supabase Auth user ID</label><input className={inputClass} {...form.register('userId')} /></div><div><label className={labelClass}>Full name</label><input className={inputClass} {...form.register('fullName')} /></div><div><label className={labelClass}>Email</label><input type="email" className={inputClass} {...form.register('email')} /></div><div><label className={labelClass}>Role</label><select className={inputClass} {...form.register('role')}><option value="STAFF">STAFF</option><option value="ADMIN">ADMIN</option><option value="OWNER">OWNER</option></select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" {...form.register('isActive')} /> Active access</label><button disabled={isPending} className="inline-flex h-10 items-center gap-2 rounded-lg bg-slate-950 px-4 text-sm font-semibold text-white"><ShieldCheck className="h-4 w-4" />Save access record</button></form><Notice message={message} /></section><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold">Approved administration records</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Name</th><th className="px-5 py-3">Email</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Status</th></tr></thead><tbody>{admins.map((admin) => <tr key={admin.id} className="border-t border-slate-100"><td className="px-5 py-3 font-semibold">{admin.full_name}</td><td className="px-5 py-3 text-slate-600">{admin.email}</td><td className="px-5 py-3"><span className="rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">{admin.role}</span></td><td className="px-5 py-3 text-slate-600">{admin.is_active ? 'Active' : 'Inactive'}</td></tr>)}</tbody></table></div>{!admins.length ? <p className="p-6 text-sm text-slate-500">No owner or administration records exist yet. Create and verify the intended Supabase Auth account before assigning a role.</p> : null}</section></div>
}
