'use client'

import Link from 'next/link'
import { useState } from 'react'
import { createCartCodOrder } from '@/lib/commerce/order-actions'
import { formatPrice } from '@/lib/services/storefront-utils'

type CartSummary = { itemCount: number; subtotal: number; deliveryCharges: { dhakaCharge: number; outsideDhakaCharge: number } }
export function CartCheckoutFlow({ cart }: { cart: CartSummary }) {
  const [form, setForm] = useState({ fullName: '', phone: '', email: '', division: 'Dhaka', district: '', area: '', address: '', postalCode: '', notes: '' })
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [success, setSuccess] = useState<{ orderNumber: string } | null>(null)
  function update(key: keyof typeof form, value: string) { setForm((current) => ({ ...current, [key]: value })) }
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setMessage(''); const result = await createCartCodOrder({ ...form, checkoutRequestId: crypto.randomUUID() }); setBusy(false); if (!result.ok) { setMessage(result.message ?? 'Unable to place your order.'); return } if (result.data) setSuccess({ orderNumber: result.data.orderNumber }); else setMessage('The order response was incomplete. Please try again.') }
  if (success) return <div className="rounded-[1.75rem] border border-emerald-200 bg-emerald-50 p-8 text-center"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">Order received</p><h1 className="mt-3 text-3xl font-black text-slate-950">Thank you for your order.</h1><p className="mt-3 text-sm text-slate-600">Your order number is <strong>{success.orderNumber}</strong>. We will contact you to confirm delivery.</p><Link href="/products" className="mt-6 inline-flex rounded-full bg-slate-950 px-5 py-3 text-sm font-black text-white">Continue shopping</Link></div>
  return <form onSubmit={submit} className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_22rem]"><section className="rounded-[1.75rem] border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-600">Secure checkout</p><h1 className="mt-2 text-3xl font-black tracking-[-0.04em] text-slate-950">Delivery details</h1><p className="mt-2 text-sm text-slate-500">Cash on Delivery is active. The server rechecks price, stock, and delivery before creating the order.</p>{message ? <p role="alert" className="mt-5 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{message}</p> : null}<div className="mt-7 grid gap-4 sm:grid-cols-2">{([['fullName','Full name'],['phone','Mobile number'],['email','Email (optional)'],['division','Division'],['district','District'],['area','Area / upazila'],['postalCode','Postal code (optional)']] as const).map(([key,label]) => <label key={key} className="text-sm font-semibold text-slate-700">{label}<input value={form[key]} onChange={(event) => update(key, event.target.value)} required={!['email','postalCode'].includes(key)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal outline-none focus:border-emerald-500" /></label>)}<label className="text-sm font-semibold text-slate-700 sm:col-span-2">Full delivery address<textarea value={form.address} onChange={(event) => update('address', event.target.value)} required rows={3} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal outline-none focus:border-emerald-500" /></label><label className="text-sm font-semibold text-slate-700 sm:col-span-2">Notes (optional)<textarea value={form.notes} onChange={(event) => update('notes', event.target.value)} rows={2} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-3 font-normal outline-none focus:border-emerald-500" /></label></div><button disabled={busy || !cart.itemCount} className="mt-7 inline-flex min-h-12 w-full items-center justify-center rounded-full bg-slate-950 px-5 py-3 text-sm font-black text-white hover:bg-emerald-600 hover:text-slate-950 disabled:opacity-50">{busy ? 'Checking details…' : 'Place Cash on Delivery order'}</button></section><aside className="h-fit rounded-[1.5rem] bg-slate-950 p-6 text-white"><p className="text-xs font-bold uppercase tracking-[0.18em] text-emerald-300">Order summary</p><div className="mt-6 flex justify-between text-sm text-slate-300"><span>{cart.itemCount} item{cart.itemCount === 1 ? '' : 's'}</span><span>{formatPrice(cart.subtotal)}</span></div><p className="mt-4 border-t border-white/10 pt-4 text-xs leading-5 text-slate-400">Delivery: Dhaka {formatPrice(cart.deliveryCharges.dhakaCharge)} · Outside Dhaka {formatPrice(cart.deliveryCharges.outsideDhakaCharge)}</p></aside></form>
}
